### ISSUE TITLE
Basic Thoughts, Architecture, and Initial Decisions

### ISSUE THREAD

**Issue by HeinousTugboat** [treytomlin/HelpQueueApp#1]
Let's get down in writing what our stated goal is, our planned scope, and try and start breaking the pieces of the project down into more manageable pieces. The central idea is to have a web dashboard where users (Tech Elevator students and staff) can login to make an appointment with instructors, and then receive push notifications when their time is ready. We should have a database backing it, where we handle authentication, push notifications, and actual scheduling.

## Front End Systems/Decisions
* First and foremost, SPA or MPA? If SPA, Angular or React? Presumably an MPA would use some combination of Spring and jQuery.
* True push notifications or polled notifications? True push is possible but requires either service workers or sockets. I'm not entirely certain on the pros and cons, but will happily learn. This should be mostly orthogonal to the previous decision.
* Design. First we'll need to think about what screens or views we will have. We can start thinking about actual visual design down the road, but the actual views will be important from the beginning.

## Back End Systems/Decisions
* Database. Java into SQL? Firebase? In Memory? How do we want to store data? What data do we want to store? What about GPDR? There isn't a lot of privacy involved here, but it's still something that should be abided even in this situation.
* Authentication Scheme? Do we want to just use regular username/password combinations? Some sort of OAuth solution? There are a lot of options here, some better than others. I don't know what the Java community favors. Do we even need an authentication or account system? We could just have people sign in, pick their role, type in their name, and process the queues that way.
* Actual scheduling system? Do we just keep it in memory and when the day's over forget everything? Do we allow longterm appointment making? Do we want to point towards future potential integration with things like Google Calendar and iCal? That may alter these decisions.
* API Design? How do we handle the actual API? Should the front end and back end be complete separate? Or should they be attached such that the backend is serving the pages and the data? This relates back to which architecture and framework we choose to work within.

----

Anyway, those're some initial thoughts we should start considering, especially going into meeting with the instructor about it. I will be completely happy to help in whatever capacity I can. I'm strongly familiar with both JS and TS, and comfortable with jQuery and Bootstrap. I can help design views, the architecture, and write templates and/or components depending on which system we settle with. Pretty much the only thing I won't be particularly helpful with is the actual Java backend, since I'm not particularly familiar with it and not particularly fond of it.

Let me know what you think.

**Comment by treytomlin** [comment]
### Front End Systems/Decisions

- SPA for sure. I think it's the best option considering our needs and skill sets. My biggest goal for this project, outside of a working application, is to learn some new skills, and apply the ones I'm learning - so considering that, I'm pretty open, although I really want to learn Angular, and you have experience in that, so unless you or Brian advise otherwise, I vote Angular.

- I'd like to do true push notifications, possibly with Firebase? Most of these Front-End decisions I'm happy to defer to you on, I'm less concerned with the particulars more than I am with learning new things.

- As far as design, I think it makes sense to limit it to laptop/desktop, since it'll only be used by the Instructors and students, and we all have/use these. 

### Back End Systems/Decisions

- I'm all for Firebase, It's another skill I'd like to gain, plus it works alongside Angular right? From what I know it seems to be a quick and lightweight option and I'm all for giving and taking the least amount of data as possible. 

- A real scheduling system that integrates with gmail/cal would be great, but I don't want us to shoot for so many features we can't complete it before the cohort ends. I'm fine with something simple and beautiful that might lack all the possible features. Especially considering we could always add to it in the future or if we think it could be a sellable product, maybe we make a lite version for Tech Elevator/GitHub, and a beefy version for us/BitBucket.

Anyhow, I'm pretty open with what we make and how we do it, I''d just like to learn some stuff and end up with a good job =)

Thanks for all your help.

**Comment by HeinousTugboat** [comment]
Sounds like a plan! I've gone ahead and stood up an empty Angular project with AngularFire 2, Angular Material, and Commitizen. It should build just fine if you do an `npm install -D` after pulling it down. I also added a bunch of resources to the README. If you can, try and get familiar with Commitizen, it's extremely useful and I like using it for both the standardized commit messages and the ability to auto-generate the changelog, including breaking changes. I'm gonna set up the initial release tonight with standard-version.

I'm otherwise gonna close this issue for now. We can start planning out MVP features and extended features in another one.
